[manifest]
version = "1.0.0"
dump_lua = true
priority = 10

# T.Red Deck
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''G.GAME.current_round.discards_left = math.max(0, G.GAME.round_resets.discards + G.GAME.round_bonus.discards)
            G.GAME.current_round.hands_left = (math.max(1, G.GAME.round_resets.hands + G.GAME.round_bonus.next_hands))'''
position = 'at'
match_indent = true
payload = '''
if not G.GAME.selected_back.effect.config.static_plays or (G.GAME.round_resets.ante)%G.GAME.win_ante == 0 and G.GAME.round_resets.ante >= 2 then
    G.GAME.current_round.discards_left = math.max(0, G.GAME.round_resets.discards + G.GAME.round_bonus.discards)
    G.GAME.current_round.hands_left = (math.max(1, G.GAME.round_resets.hands + G.GAME.round_bonus.next_hands))
end'''

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''G.GAME.current_round.discards_left = math.max(0, G.GAME.round_resets.discards + G.GAME.round_bonus.discards)
            G.GAME.current_round.hands_left = (math.max(1, G.GAME.round_resets.hands + G.GAME.round_bonus.next_hands))'''
position = 'at'
match_indent = true
payload = '''
if not G.GAME.selected_back.effect.config.static_plays or (G.GAME.round_resets.ante)%G.GAME.win_ante == 0 and G.GAME.round_resets.ante >= 2 then
    G.GAME.current_round.discards_left = math.max(0, G.GAME.round_resets.discards + G.GAME.round_bonus.discards)
    G.GAME.current_round.hands_left = (math.max(1, G.GAME.round_resets.hands + G.GAME.round_bonus.next_hands))
end'''

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''G.jokers.cards[i]:calculate_joker({ending_shop = true})
      end'''
position = 'after'
match_indent = true
payload = '''
G.GAME.selected_back:trigger_effect({context = 'ending_shop'})
'''

# T.Yellow Deck
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''{n=G.UIT.T, config={text = localize('$')..format_ui_value(config.dollars), scale = 1.2*scale, colour = G.C.WHITE, shadow = true, juice = true}}'''
position = 'at'
match_indent = true
payload = '''
{n=G.UIT.T, config={text = (not G.GAME.selected_back.effect.config.money_mult) and (localize('$')..format_ui_value(config.dollars)) or (format_ui_value(config.dollars * G.GAME.selected_back.effect.config.money_mult + G.GAME.selected_back.effect.config.money_mult_min) .. "X" .. localize('$')) , scale = 1.2*scale, colour = G.C.WHITE, shadow = true, juice = true}}
'''

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''G.FUNCS.cash_out = function(e)'''
position = 'after'
match_indent = true
payload = '''
if G.GAME.selected_back.effect.config.money_mult then
    G.GAME.current_round.dollars = math.floor((G.GAME.current_round.dollars * G.GAME.selected_back.effect.config.money_mult + G.GAME.selected_back.effect.config.money_mult_min) * G.GAME.dollars) - G.GAME.dollars
end
'''

# T.Nebula Deck

#level_up_hand(used_tarot, handname, nil, -1)
#level_up_hand(used_tarot, self.ability.consumeable.hand_type)
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''level_up_hand(used_tarot, self.ability.consumeable.hand_type)'''
position = 'at'
match_indent = true
payload = '''
level_up_hand(used_tarot, self.ability.consumeable.hand_type, nil, G.GAME.selected_back.effect.config.alt_planet_levels or 1)
if G.GAME.selected_back.effect.config.negative_planet_levels then
    local valid_hands = {}
    for hand_key, hand in pairs(G.GAME.hands) do 
        if hand.visible and hand.level > 0 then
            valid_hands[#valid_hands+1] = hand_key
        end 
    end
    if valid_hands then
        local random_hand = pseudorandom_element(valid_hands, pseudoseed('rand_level_down'))
        update_hand_text({sound = 'button', volume = 0.7, pitch = 0.8, delay = 0.3}, {handname=localize(random_hand, 'poker_hands'),chips = G.GAME.hands[random_hand].chips, mult = G.GAME.hands[random_hand].mult, level=G.GAME.hands[random_hand].level})
        level_up_hand(used_tarot, random_hand, nil, -G.GAME.selected_back.effect.config.negative_planet_levels)
    end
end
'''
